# Generated by Django 4.1.3 on 2022-11-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=2048)),
                ('deviceType', models.CharField(max_length=256)),
            ],
        ),
    ]
